# Basic authorization with SASL (Plaintext to Kafka and DigestMD5 to Zookeeper)
---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    ports:
      - '31000:31000'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider -Djava.security.auth.login.config=/opt/security/zookeeper-server.jaas"
      KAFKA_JMX_HOSTNAME: "localhost"
      KAFKA_JMX_PORT: 31000
    volumes:
      - ./security:/opt/security

  Broker1:
    image: confluentinc/cp-server:5.5.1
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: REPLICATION      
      KAFKA_LISTENERS: "EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:9093,REPLICATION://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:9092,INTERNAL://Broker1:9093,REPLICATION://Broker1:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,REPLICATION:SASL_PLAINTEXT"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_REPLICATION_SASL_ENABLED_MECHANISMS: PLAIN
      
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      
      KAFKA_SUPER_USERS: "User:broker;User:admin"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_ZOOKEEPER_SET_ACL: "true"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/security/kafka-server.jaas"
      
      
      
      KAFKA_CONFLUENT_SECURITY_EVENT_ROUTER_CONFIG: "{\"routes\":{\"crn:///kafka=*/group=*\":{\"consume\":{\"allowed\":\"confluent-audit-log-events\",\"denied\":\"confluent-audit-log-events\"}},\"crn:///kafka=*/topic=*\":{\"produce\":{\"allowed\":\"confluent-audit-log-events\",\"denied\":\"confluent-audit-log-events\"},\"consume\":{\"allowed\":\"confluent-audit-log-events\",\"denied\":\"confluent-audit-log-events\"}},\"crn:///kafka=*/topic=_*\":{\"consume\":{\"allowed\":\"\",\"denied\":\"\"},\"produce\":{\"allowed\":\"\",\"denied\":\"\"},\"other\":{\"allowed\":\"\",\"denied\":\"\"}},\"crn:///kafka=*/topic=confluent-audit-log-events*\":{\"consume\":{\"allowed\":\"\",\"denied\":\"\"},\"produce\":{\"allowed\":\"\",\"denied\":\"\"},\"other\":{\"allowed\":\"\",\"denied\":\"\"}}},\"destinations\":{\"topics\":{\"confluent-audit-log-events\":{\"retention_ms\":7776000000}}},\"default_topics\":{\"allowed\":\"confluent-audit-log-events\",\"denied\":\"confluent-audit-log-events\"},\"excluded_principals\":[\"User:broker\"]}"
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./security:/opt/security
      - ./config/kafka/log4j.properties.template:/etc/confluent/docker/log4j.properties.template
      - ./logs:/var/log/kafka/
      
  Broker2:
    image: confluentinc/cp-server:5.5.1
    ports:
      - '19092:19092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: REPLICATION      
      KAFKA_LISTENERS: "EXTERNAL://0.0.0.0:19092,INTERNAL://0.0.0.0:19093,REPLICATION://0.0.0.0:19094"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:19092,INTERNAL://Broker2:19093,REPLICATION://Broker2:19094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,REPLICATION:SASL_PLAINTEXT"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_REPLICATION_SASL_ENABLED_MECHANISMS: PLAIN
      
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      
      KAFKA_SUPER_USERS: "User:broker;User:admin"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_ZOOKEEPER_SET_ACL: "true"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/security/kafka-server.jaas"
      
      
      
      KAFKA_CONFLUENT_SECURITY_EVENT_ROUTER_CONFIG: "{\"routes\":{\"crn:///kafka=*/group=*\":{\"consume\":{\"allowed\":\"confluent-audit-log-events\",\"denied\":\"confluent-audit-log-events\"}},\"crn:///kafka=*/topic=*\":{\"produce\":{\"allowed\":\"confluent-audit-log-events\",\"denied\":\"confluent-audit-log-events\"},\"consume\":{\"allowed\":\"confluent-audit-log-events\",\"denied\":\"confluent-audit-log-events\"}},\"crn:///kafka=*/topic=_*\":{\"consume\":{\"allowed\":\"\",\"denied\":\"\"},\"produce\":{\"allowed\":\"\",\"denied\":\"\"},\"other\":{\"allowed\":\"\",\"denied\":\"\"}},\"crn:///kafka=*/topic=confluent-audit-log-events*\":{\"consume\":{\"allowed\":\"\",\"denied\":\"\"},\"produce\":{\"allowed\":\"\",\"denied\":\"\"},\"other\":{\"allowed\":\"\",\"denied\":\"\"}}},\"destinations\":{\"topics\":{\"confluent-audit-log-events\":{\"retention_ms\":7776000000}}},\"default_topics\":{\"allowed\":\"confluent-audit-log-events\",\"denied\":\"confluent-audit-log-events\"},\"excluded_principals\":[\"User:broker\"]}"
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./security:/opt/security
      - ./config/kafka/log4j.properties.template:/etc/confluent/docker/log4j.properties.template
      - ./logs:/var/log/kafka/
      
      
  Broker3:
    image: confluentinc/cp-server:5.5.1
    ports:
      - '29092:29092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: REPLICATION      
      KAFKA_LISTENERS: "EXTERNAL://0.0.0.0:29092,INTERNAL://0.0.0.0:29093,REPLICATION://0.0.0.0:29094"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:29092,INTERNAL://Broker3:29093,REPLICATION://Broker3:29094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,REPLICATION:SASL_PLAINTEXT"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      
      KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_REPLICATION_SASL_ENABLED_MECHANISMS: PLAIN
      
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      
      KAFKA_SUPER_USERS: "User:broker;User:admin"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_ZOOKEEPER_SET_ACL: "true"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/security/kafka-server.jaas"
      
      
      
      KAFKA_CONFLUENT_SECURITY_EVENT_ROUTER_CONFIG: "{\"routes\":{\"crn:///kafka=*/group=*\":{\"consume\":{\"allowed\":\"confluent-audit-log-events\",\"denied\":\"confluent-audit-log-events\"}},\"crn:///kafka=*/topic=*\":{\"produce\":{\"allowed\":\"confluent-audit-log-events\",\"denied\":\"confluent-audit-log-events\"},\"consume\":{\"allowed\":\"confluent-audit-log-events\",\"denied\":\"confluent-audit-log-events\"}},\"crn:///kafka=*/topic=_*\":{\"consume\":{\"allowed\":\"\",\"denied\":\"\"},\"produce\":{\"allowed\":\"\",\"denied\":\"\"},\"other\":{\"allowed\":\"\",\"denied\":\"\"}},\"crn:///kafka=*/topic=confluent-audit-log-events*\":{\"consume\":{\"allowed\":\"\",\"denied\":\"\"},\"produce\":{\"allowed\":\"\",\"denied\":\"\"},\"other\":{\"allowed\":\"\",\"denied\":\"\"}}},\"destinations\":{\"topics\":{\"confluent-audit-log-events\":{\"retention_ms\":7776000000}}},\"default_topics\":{\"allowed\":\"confluent-audit-log-events\",\"denied\":\"confluent-audit-log-events\"},\"excluded_principals\":[\"User:broker\"]}"
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./security:/opt/security
      - ./config/kafka/log4j.properties.template:/etc/confluent/docker/log4j.properties.template
      - ./logs:/var/log/kafka/
